config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  #home pages
  root "picks#index"
  
  #for all pick routes
  resources :picks

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pick.rb
class Pick < ApplicationRecord
    validates :team_1, :team_2, :sport, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController

    def index
        @picks = Pick.all
    end

    def show
        @pick = Pick.find(params[:id])
    end 

    def new 
        @pick = Pick.new
    end 

    def create 
        @pick = Pick.new(pick_params)
        @pick.save 
        
        if @pick.save
            flash[:notice] = "Pick was created."
            redirect_to pick_path(@pick)
        else  
            flash[:alert] = "Pick not created. Try again."
            render :new
        end 
    end 

    def edit
        @pick = Pick.find(params[:id])
    end 

    def update
        @pick = Pick.find(params[:id])

        if @pick.update(pick_params)
            redirect_to pick_path(@pick)
        else  
            flash[:errors] = @pick.errors.full_messages
            render :edit
        end 
    end 

    def destroy
        @pick = Pick.find(params[:id])
        @pick.destroy 

        redirect_to picks_path
    end 

    private 

    def pick_params
        params.require(:pick).permit(
            :team_1,
            :team_2,
            :sport,
            :time
        )
    end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/picks_helper.rb
module PicksHelper
end

app/views/application/_errors.html.erb
<% if !!flash[:errors] %>
<ul>
<% flash[:errors].each do |e| %>
  <li><%= e %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gameon Picks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/picks/_form.html.erb
<%= form_for(pick) do |f| %>
    <label class="label">Team 1:</label>
    <%= f.text_field :team_1 %><br><br>

    <label class="label">Team 2:</label>
    <%= f.text_field :team_2 %><br><br>

    <label class="label">Sport:</label>
    <%= f.text_field :sport %><br><br>

    <label class="label">Time:</label>
    <%= f.text_field :time %><br><br>

    <input type="submit" value="Submit" class="button is-primary">
<% end %>

app/views/picks/_list.html.erb
<ul>
<% picks.each do |p| %>

    <li><%= link_to p.team_1 + p.team_2, pick_path(p) %>
   </li> 
   
<% end %>
</ul>

app/views/picks/edit.html.erb
<section class="hero is-primary is-bold">
    <div class="hero-body">
        <div class="container">
            <h2 class="subtitle">Edit Your Pick</h2>
        </div>
    </div>
</section>
<br>

<%= render "application/errors" %>
<%= render partial: "form", locals: {pick: @pick} %>

<br>


<%= form_tag(pick_path(@pick), method: "delete") do %>
    <input type="submit" value="Delete" class="button is-danger">
<% end %>

app/views/picks/index.html.erb
<h1> All Games/Picks </h1>

<div>
    <strong><%= link_to "CREATE A NEW PICK", new_pick_path %></strong>
    </div>
    <br>
   


<ul>
<div>
<%= render partial: "picks/list", locals: {picks: @picks} %>
</div>
</ul>

<br>

 <div>

app/views/picks/new.html.erb
<h1>New Pick</h1>

<%= render 'form', pick: @pick %>
<%= link_to 'Back', picks_path %>

app/views/picks/show.html.erb
<br>
    <%= link_to "Edit Pick", edit_pick_path(@pick) %> <br>
<br>


<p>
  <strong>Team 1:</strong>
  <%= @pick.team_1 %>
  <br>
  <strong> <%= link_to "| PICK |"%>  </strong>
   </p>
 
<p>
  <strong>Team 2:</strong>
  <%= @pick.team_2 %>
  <br>
  <strong> <%= link_to "| PICK |"%>  </strong>
</p>
 
<p>
  <strong>Sport:</strong>
  <%= @pick.sport %>
</p>
 
<p>
  <strong>Time:</strong>
  <%= @pick.time %>
</p>
<br>

<h2>
<%= link_to 'BACK', picks_path %>

</h2>